#!/usr/bin/env python

Import("env")
Import("env_modules")

env_firebase_analytics = env_modules.Clone()

if env["platform"] == "ios":
    env_firebase_analytics.add_source_files(env.modules_sources, "register_types.cpp")
    env_firebase_analytics.add_source_files(env.modules_sources, "firebase_analytics.mm")
